Fix loading GAP.jl when the package dir is read-only (#1353)
If the GAP.jl `pkg` subdirectory was read-only, the package failed
to load because we tried to create a pidlock file in there. This
resulted in errors like this:
```
julia> using Oscar
ERROR: InitError: IOError: open("/SOME/PATH/depot/packages/GAP/TS6pI/pkg/JuliaInterface.lock", 194, 292): permission denied (EACCES)
Stacktrace:
  [1] _uv_error(prefix::String, c::Int32)
    @ Base ./libuv.jl:114
  [2] uv_error
    @ ./libuv.jl:113 [inlined]
  [3] open(path::String, flags::UInt16, mode::UInt16)
    @ Base.Filesystem ./filesystem.jl:190
  [4] tryopen_exclusive(path::String, mode::UInt16)
    @ FileWatching.Pidfile JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:215
  [5] open_exclusive(path::String; mode::UInt16, poll_interval::Int64, wait::Bool, stale_age::Int64, refresh::Float64)
    @ FileWatching.Pidfile JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:242
  [6] open_exclusive
    @ JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:235 [inlined]
  [7] mkpidlock(at::String, pid::Int32; stale_age::Int64, refresh::Float64, kwopts::@Kwargs{})
    @ FileWatching.Pidfile JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:66
  [8] mkpidlock
    @ JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:61 [inlined]
  [9] mkpidlock(f::GAP.Setup.var"#locate_JuliaInterface_so##0#locate_JuliaInterface_so##1"{String, Vector{UInt8}, String}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:91
 [10] mkpidlock
    @ JULIADIR/share/julia/stdlib/v1.12/FileWatching/src/pidfile.jl:88 [inlined]
 [11] locate_JuliaInterface_so()
    @ GAP.Setup /scratch/Oscar-playground/depot/packages/GAP/TS6pI/src/setup.jl:224
 [12] __init__()
```

Fix this by refactoring `locate_JuliaInterface_so`. It now only takes the pidlock when
it is really necessary.